-- Baseline schema matching the current JPA entities exactly (PostgreSQL variant).
-- The H2 variant used by tests lives in db/migration/h2/. They differ only in the
-- type of story.body: @Lob String maps to CLOB on H2 and to OID (large object)
-- on PostgreSQL, which is what Hibernate 6 validates against.
-- Table names follow the default Spring Boot naming strategy:
-- users/tokens are explicit @Table names; Story has no @Table so it maps to "story".

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(512),
    token_type VARCHAR(255),
    revoked BOOLEAN NOT NULL,
    expired BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    user_id BIGINT,
    CONSTRAINT uk_tokens_token UNIQUE (token),
    CONSTRAINT fk_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE story (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    audio_url VARCHAR(255),
    background_image_url VARCHAR(255),
    body OID
);
